services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - oddspark-db:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
  api:
    build:
      context: ./api/
    restart: always
    command: fastapi dev --host 0.0.0.0 --port 8080
    ports:
      - "9000:8080"
    volumes:
      - "./api/migrations:/app/migrations"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    develop:
      watch:
        - path: ./api
          action: sync
          target: /app
          ignore:
            - ./api/.venv
        - path: ./api/pyproject.toml
          action: rebuild
volumes:
  oddspark-db: