"""Adding attack type relationship

Revision ID: 65cdfbb33e7a
Revises: 70f3ce306c20
Create Date: 2025-03-18 00:21:43.609349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '65cdfbb33e7a'
down_revision: Union[str, None] = '70f3ce306c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spark', sa.Column('attack_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'spark', 'attacktype', ['attack_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spark', type_='foreignkey')
    op.drop_column('spark', 'attack_type_id')
    # ### end Alembic commands ###
