"""spark tables unique name constraints

Revision ID: 7f9c1e7eaf95
Revises: 65cdfbb33e7a
Create Date: 2025-03-18 00:58:21.993438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7f9c1e7eaf95'
down_revision: Union[str, None] = '65cdfbb33e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attacktype', ['name'])
    op.create_unique_constraint(None, 'spark', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spark', type_='unique')
    op.drop_constraint(None, 'attacktype', type_='unique')
    # ### end Alembic commands ###
